[build]
  command = "bash netlify/build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_PG_FORCE_NATIVE = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
